version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:11.4.0
    steps:  
      - checkout
      - run: 
        command: npm start
        background: true
      - run: npm install
      - run: npm test
          