version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:11.4.0
    steps:  
      - checkout
      - run: 
          name: Running server
          command: npm start
          background: true
      - run: npm install
      - run: sleep 50 && npm test
          