version: 2.1
jobs:
  build:
    working_directory: ~/demo-react-native
    docker:
      - image: circleci/node:8
    steps:
    docker:
      - image: circleci/node:8
    steps:  
      - run: npm install
      - run: 
        name: jest tests 
        command: |
          jest sum.test.js
